### ISSUE TITLE
main test build is broken: nuget flatcontainer_download call site missed by #3205

### ISSUE THREAD

**Issue by brandonrc** [artifact-keeper/artifact-keeper#3221]
`cargo build --lib --tests` fails on a pristine `origin/main` (`1743098`), so the whole test suite is uncompilable and `cargo test` / nextest cannot run at all.

```
error[E0277]: the trait bound `Path<(String, String, String, String)>: Default` is not satisfied
    --> backend/src/api/handlers/nuget.rs:4659:17
4659 |                 Default::default(),
     |                 ^^^^^^^^^^^^^^^^^^

error[E0061]: this function takes 4 arguments but 3 arguments were supplied
    --> backend/src/api/handlers/nuget.rs:4651:24
4651 |               let resp = super::flatcontainer_download(
     | argument #4 of type `download_telemetry::DownloadContext` is missing

error: could not compile `artifact-keeper-backend` (lib test) due to 2 previous errors
```

## Cause: parallel-merge signature drift

- #3205 (`5760936`) added `Extension(auth): Extension<Option<AuthExtension>>` to `flatcontainer_download` and updated four of its five test call sites (`nuget.rs:3305`, `:4498`, `:4837`, `:4982`).
- #2919 (`a6acc9f`) concurrently **added** a fifth call site at `nuget.rs:4651` using the old 3-argument signature.

Both PRs were green independently; the conflict is semantic, not textual, so git merged them cleanly and main broke.

## Fix

One line — add the missing argument at `nuget.rs:4652`, matching the other four call sites:

```rust
axum::Extension(tdh::admin_auth_ext()),
```

This is already included in PR #3217 and PR #3218 (both needed it to run their own tests), so merging either one repairs main. Filing separately because main being red is worth its own record, and because it recurs: this is the same class as the previously-seen handler-vs-test signature drift from parallel green PRs.

## Suggested follow-up

CI appears not to be gating on a test-target **compile** for merges to main, or these would have been caught. Worth confirming that the required checks include something that compiles `--all-targets`, and considering a post-merge tripwire build after a burst of parallel merges touching shared handler signatures.

**Comment by brandonrc** [comment]
Fixed on main by #3215 — `flatcontainer_download` call site in `backend/src/api/handlers/nuget.rs` now passes the `Extension(None)` parameter added by #3205. Verified `SQLX_OFFLINE=true cargo build --lib --tests` is clean on main.
