### ISSUE TITLE
main fails to compile: build_cached_artifact_response missing cache_cached_at / cache_expires_at (E0063)

### ISSUE THREAD

**Issue by knowinglyAnonymous** [artifact-keeper/artifact-keeper#1578]
## Symptom

`main` does not compile. `cargo build`/`cargo test` fail with:

```
error[E0063]: missing fields `cache_cached_at` and `cache_expires_at` in initializer of `repositories::ArtifactResponse`
    --> backend/src/api/handlers/repositories.rs:1887:5
```

The scheduled CI on `main` is red as a result.

## Root cause

Two PRs that were each green on their own branch collided on merge:

- **#1567** added `build_cached_artifact_response()` in `backend/src/api/handlers/repositories.rs`.
- **#1542** added the required fields `cache_cached_at` / `cache_expires_at` to the `ArtifactResponse` struct.

`#1542`'s branch predated `#1567`, so it never saw the new initializer and didn't update it. After both landed, that one initializer is missing the two now-required fields.

## Reproduction

```bash
git checkout main
cd backend && cargo build
# error[E0063]: missing fields cache_cached_at and cache_expires_at
```

## Fix

Populate the two fields in `build_cached_artifact_response`. A cached-listing entry is a live proxy-cache object, so `cache_cached_at` is exactly `entry.cached_at`; the sidecar projection (`CachedArtifactEntry`) carries no expiry, so `cache_expires_at` stays `None` (the per-artifact metadata endpoint from #1541 surfaces expiry). Both fields are `skip_serializing_if = Option::is_none`, so the listing wire shape is unchanged.

PR incoming.

## Additional context

Related: #1542, #1567, #1541.

**Comment by knowinglyAnonymous** [comment]
Resolved by #1592 (merged), which applies the same fix to `build_cached_artifact_response()` (`cache_cached_at: Some(entry.cached_at)`, `cache_expires_at: None`) and restored the build. `main` now compiles and the npm follow-up #1581 has merged cleanly on top. Closing as completed. Thanks @brandonrc!
