### ISSUE TITLE
backend integration tests fail to compile: Config missing rate_limit_trusted_proxy_cidrs after #2023

### ISSUE THREAD

**Issue by brandonrc** [artifact-keeper/artifact-keeper#2060]
## Problem

PR #2046 (merged, based on #2023 rate-limit work) added the `rate_limit_trusted_proxy_cidrs` field to the `Config` struct and updated the in-source test-helper Config literals, but two integration-test files were missed:

- `backend/tests/composer_packages_index_tests.rs`
- `backend/tests/incus_upload_tests.rs`

These files build `Config { ... }` directly and now fail to compile:

```
error[E0063]: missing field `rate_limit_trusted_proxy_cidrs` in initializer of `...::Config`
```

The `Check Rust (clippy)` CI step OOM-killed on #2046, masking the regression; the PR was then admin-merged.

## Impact

`cargo check --tests`, `cargo clippy --all-targets`, and `cargo test --all-targets` all fail on `main`. Any contributor running tests locally or any CI run that includes test compilation will be broken.

## Fix

Add `rate_limit_trusted_proxy_cidrs: Vec::new(),` to the `Config { ... }` literal in each affected file, matching the pattern used in the sibling helpers (e.g. `backend/src/api/handlers/test_db_helpers.rs`).
