### ISSUE TITLE
main fails to compile: ArtifactResponse missing cache_cached_at/cache_expires_at

### ISSUE THREAD

**Issue by brandonrc** [artifact-keeper/artifact-keeper#1591]
## Problem

`main` does not compile. `cargo check --workspace` and the CI "Check Rust" + "Backend Unit Tests" jobs fail with:

```
error[E0063]: missing fields `cache_cached_at` and `cache_expires_at` in initializer of `repositories::ArtifactResponse`
    --> backend/src/api/handlers/repositories.rs:1887
```

### Root cause

A semantic merge collision between two separately-green PRs:
- #1542 added the required `cache_cached_at`/`cache_expires_at` fields to `ArtifactResponse`.
- #1567 added `build_cached_artifact_response()`, which constructs `ArtifactResponse` without those fields.

Each passed CI on its own branch; the break only exists in the merged result. Every open PR is currently red because they all branch off the broken `main`.

## Fix

Populate the two fields in `build_cached_artifact_response()`. The input is a `CachedArtifactEntry` (proxy-cache projection), which carries `cached_at` but no expiry, so:

- `cache_cached_at: Some(entry.cached_at)` (real value)
- `cache_expires_at: None`

Verified locally green with the full CI gate set: `cargo fmt --all -- --check`, `cargo clippy --workspace --all-targets -- -D warnings`, and `cargo test --workspace --lib`.

Supersedes the partial fixes #1579 and #1588 (both fixed the lib site but were not verified against `clippy --all-targets`).

## Follow-up

This is the merge-collision class that local hooks cannot catch. Enabling branch protection "require branches up to date before merging" / a merge queue would prevent a recurrence (separate issue).
